use dynamic locations

diff --git a/dev-tools/scripts/rebuild-generic-scratch-org b/dev-tools/scripts/rebuild-generic-scratch-org
--- a/dev-tools/scripts/rebuild-generic-scratch-org
+++ b/dev-tools/scripts/rebuild-generic-scratch-org
@@ -17,12 +17,30 @@
 ##
 ###
 #### LOAD SHARED FUNCTIONS LIBRARY #################################################################
-###
-##
 #
 # Make sure that the shared-functions.sh script exists.
-if [ ! -r `dirname $0`/lib/shared-functions.sh ]; then
-  echo "\nFATAL ERROR: `tput sgr0``tput setaf 1`Could not load dev-tools/lib/shared-functions.sh.  File not found.\n"
+# Start from the current directory
+current_dir=$(realpath .)
+
+# Look for the "dev-tools" directory by traversing up the directory structure
+while [[ "$current_dir" != "/" ]]; do
+  if [[ -d "$current_dir/dev-tools" ]]; then
+    root_dir="$current_dir/dev-tools"
+    break
+  fi
+  current_dir=$(dirname "$current_dir")
+done
+
+# Check if the "dev-tools" directory was found
+if [[ -z "$root_dir" ]]; then
+  echo "FATAL ERROR: `tput sgr0``tput setaf 1`Could not find the dev-tools directory."
+  exit 1
+fi
+
+# Now you can use "$root_dir" as the root directory
+lib_path="$root_dir/lib/shared-functions.sh"
+if [[ ! -r "$lib_path" ]]; then
+  echo "FATAL ERROR: `tput sgr0``tput setaf 1`Could not load $lib_path. File not found."
   exit 1
 fi
 
@@ -31,7 +49,7 @@ REQUESTED_OPERATION="REBUILD_GENERIC_SCRATCH_ORG"
 
 # Load the shared-functions.sh library.  This action will also cause the
 # config variables from dev-tools/lib/local-config.sh to be loaded.
-source `dirname $0`/lib/shared-functions.sh
+source "$lib_path"
 #
 ##
 ###
